name: C++ CI with vcpkg  
on:  
  push:  
    branches: [ "master" ]  
  pull_request:  
    branches: [ "master" ]  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v4 
    - name: Install vcpkg  
      run: git clone https://github.com/microsoft/vcpkg.git && cd vcpkg  && ./bootstrap-vcpkg.sh  && echo "::add-path::${PWD}"  
    - name: Install dependencies with vcpkg  
      working-directory: ${{github.workspace}}
      run: vcpkg install --triplet x64-linux --manifest-mode  
    - name: Configure and build  
      run: mkdir build && cd build && cmake --build . --config Release  
